# Generated by Django 3.2.5 on 2021-07-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='num_of_students',
            field=models.IntegerField(default=10),
        ),
    ]
