# Generated by Django 3.2.5 on 2021-07-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_auto_20210730_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers',
            name='age',
        ),
        migrations.AddField(
            model_name='teachers',
            name='subject',
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
    ]
