# Generated by Django 3.2.5 on 2021-07-31 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_auto_20210730_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='age',
            field=models.IntegerField(default=25),
        ),
    ]
