# Generated by Django 3.2.5 on 2021-08-09 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_teachers_age'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teachers',
            new_name='Teacher',
        ),
    ]
